version: '3.8'
services:
#  frontend:
#    build:
#      context: ./frontend
#    container_name: frontend
#    ports:
#      - "8080:80"
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    depends_on:
      - db
  db:
    image: postgres:16.0 
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: js_drf
    container_name: db
    ports:
      - "5433:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:  
  local_pgdata:  